# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Code\Projek DBTDB\do_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 150)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMaximumSize(QtCore.QSize(400, 300))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_2 = QtWidgets.QWidget(self.widget_4)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.do_no_lineText = QtWidgets.QLineEdit(self.widget_2)
        self.do_no_lineText.setObjectName("do_no_lineText")
        self.verticalLayout.addWidget(self.do_no_lineText)
        self.warning = QtWidgets.QLabel(self.widget_2)
        self.warning.setObjectName("warning")
        self.verticalLayout.addWidget(self.warning)
        self.horizontalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.widget_4)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.do_date_edit = QtWidgets.QDateEdit(self.widget_3)
        self.do_date_edit.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.do_date_edit.setCalendarPopup(True)
        self.do_date_edit.setObjectName("do_date_edit")
        self.verticalLayout_2.addWidget(self.do_date_edit)
        self.horizontalLayout.addWidget(self.widget_3)
        self.verticalLayout_3.addWidget(self.widget_4)
        self.submit_btn = QtWidgets.QPushButton(self.widget)
        self.submit_btn.setObjectName("submit_btn")
        self.verticalLayout_3.addWidget(self.submit_btn)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "DO. No"))
        self.do_no_lineText.setPlaceholderText(_translate("Form", "Ex : 000/DO/TDB/AAA-BBB/III/2025"))
        self.warning.setText(_translate("Form", "DO. No wajib diisi"))
        self.label_3.setText(_translate("Form", "DO. Date"))
        self.do_date_edit.setDisplayFormat(_translate("Form", "d/M/yyyy"))
        self.submit_btn.setText(_translate("Form", "SUBMIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
